import { MantineProvider } from "@mantine/core";
import type { NextPage } from "next";
import Head from "next/head";
import { BioSection } from "../components/sections/BioSection/BioSection";
import { HeroSection } from "../components/sections/HeroSection/HeroSection";
import styles from "../styles/Home.module.css";
import { BlogSection } from "../components/sections/Blog Section/BlogSection";

interface IProps {
  posts: any;
  content: any;
}

const Home: NextPage<IProps> = (props: IProps) => {
  const { posts, content } = props;

  return (
    <MantineProvider withGlobalStyles withNormalizeCSS>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* Hero Section */}
        <HeroSection />
        <main className={styles.main}>
          {/* About Section */}
          <BioSection />

          {/* Blog Section */}
          <BlogSection posts={posts} />

          {/* Contact section */}
        </main>

        <footer className={styles.footer}></footer>
      </div>
    </MantineProvider>
  );
};

export async function getStaticProps() {
  // TODO: this should all happen in a serverless function that returns
  // formatted data
  // filter blogs for published
  // filter content for value present

  return {
    props: { content: {}, posts: [] },
  };
}

export default Home;
